---
ansible_python_interpreter: /usr/bin/python3

app_user: "donalo"

# This path is temporal and will make use of `ansistrano_deploy_to` and
# `shared_path` once we adopt Ansistrano for deployments
unicorn_socket: "/var/www/donalo/shared/sockets/unicorn.donalo.sock"

ruby_version: "{{ lookup('file', '../.ruby-version') }}"

hetzner_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64656138386130303666663738316537643462653864373563313839356161333363613530366238
  3932396462643637333038336133626636316139636230370a613634666438356135376635353938
  38633965613737366262663136613032353938336361396135333266383537353030323561326435
  3562343732383737370a643462333831386261323238323466353362356462353233313936316365
  65303861326632633339633763613236653435653664323763643935313461376266653663633430
  38666530366335353261333836643765396461653431313362363932336136616161373433623433
  34636534306332303066663566353662636464643538653530326163363836386135386432373265
  62616562343465666366
